name: emnlp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - freetype
  - hdf5
  - lz4-c
  - mpc
  - mpfr
  - ncurses
  - numpy
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pcre2
  - pillow
  - pytorch
  - pytorch-lightning
  - torchaudio
  - torchmetrics
  - torchvision
